Show instruction on a user's first visit
octokatherine/word-master pull request #12
Opened 2021-12-31 12:14 UTC by wilsonych

2021-12-31 20:34 UTC, octokatherine requested changes
A couple suggested changes but this is great, thank you!

2021-12-31 20:34 UTC, octokatherine commented on src/App.js
> +        onRequestClose={() => handleInfoClose()}
```suggestion
        onRequestClose={handleInfoClose}
```

2021-12-31 20:34 UTC, octokatherine commented on src/App.js
> +          onClick={() => handleInfoClose()}
```suggestion
          onClick={handleInfoClose}
```

2022-01-02 05:54 UTC, wilsonych commented
Thanks for your suggestion

2022-01-02 06:13 UTC, octokatherine approved these changes

2022-01-02 06:13 UTC, merged